name = "Skipper"
uuid = "fc65d762-6112-4b1c-b428-ad0792653d81"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.5"

[weakdeps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"

[extensions]
AccessorsExt = "Accessors"

[compat]
Accessors = "0.1"
julia = "1.6"

[extras]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
